Create SPI structure and add Webhook functionality
opensearch-project/notifications pull request #176
Opened 2021-06-02 07:38 UTC by zhongnansu

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-06-03 23:51 UTC, joshuali925 approved these changes
LGTM

2021-06-03 23:51 UTC, joshuali925 commented on notifications/spi/build.gradle
> + * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
not an issue- i don't think we need this unless the same file also exists in opendistro repo

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/Notification.kt
> +                    val channel = ChannelFactory.getNotificationChannel(message.configType)
is getNotificationChannel required to run in privileged mode?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/ChannelFactory.kt
> +    override fun getNotificationChannel(channelType: ChannelType): NotificationChannel<BaseMessage, *> {
instead of * can we use some base interface?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private val TIMEOUT_MILLISECONDS = TimeValue.timeValueSeconds(5).millis().toInt()
please add TODO to get these values from configuration.

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private val logger = LogManager.getLogger(ChannelHttpClient::class.java)
can we use lazy logger like `private val log by logger(Xyz::class.java)`

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/webhook/WebhookChannel.kt
> +    var channelHttpClient: ChannelHttpClient = ChannelHttpClientPool.httpClient
I dont see this getting changed. can this be val instead of var?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private var HTTP_CLIENT: CloseableHttpClient = createHttpClient()
Can we take this as optional constructor parameter and make it val? I believe it is var only for testing purpose

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClientPool.kt
> +    val httpClient: ChannelHttpClient = ChannelHttpClient()
why is this called pool when only 1 item is present? are we reusing same ? how is httpClient is getting closed?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    configType: ChannelType,
if Webhook behavior changes w.r.t configType then can we separate into multiple classes inheriting base class?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    override fun toString(): String {
is it required to be overriding toString? if so then we should also make sure that this object is not logged

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    val headerParams: Map<String, String>? = null,
may be this can be done non-null?

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/ChannelType.kt
> +enum class ChannelType { None, Slack, Chime, Webhook, Email }
can we have different naming convention for spi? probably destination? just a thought

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/ChannelType.kt
> +enum class ChannelType { None, Slack, Chime, Webhook, Email }
Also None is not required as there is no storing/parsing for spi I believe.

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/MessageContent.kt
> +    data class Attachment(
if we nest a class then this class is not easily accessible outside the project. separate out if that is not desired.

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/MessageContent.kt
> +    data class Attachment(
We can also use different naming convention to avoid conflicts

2021-06-08 22:27 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/BaseMessage.kt
> +    var title: String,
why are these `var`s?

2021-06-09 18:04 UTC, zhongnansu commented on notifications/build.gradle
> +    args "src/**/*.kt", "spi/**/*.kt"
will add the spi/build.gradle

2021-06-09 18:05 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/Notification.kt
> +class Notification private constructor() {
will do

2021-06-09 18:06 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private val logger = LogManager.getLogger(ChannelHttpClient::class.java)
will create helper funtion same as what we use in common-utils

2021-06-09 19:49 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/Notification.kt
> +                    val channel = ChannelFactory.getNotificationChannel(message.configType)
I think not, let me move it out of the pridileged block

2021-06-09 19:54 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    val headerParams: Map<String, String>? = null,
This is set to distinguish slack/chime(with no header params) and custom webhook(with headers)

2021-06-09 20:01 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/ChannelType.kt
> +enum class ChannelType { None, Slack, Chime, Webhook, Email }
will remove None and replace `channel` with `destination` where I have for class name and other naming in spi

2021-06-09 21:49 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    val headerParams: Map<String, String>? = null,
will create a child class `CustomWebhookMessage`, then we can make `headerparams`non-null as your other comment point out

2021-06-10 00:30 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/ChannelFactory.kt
> +    override fun getNotificationChannel(channelType: ChannelType): NotificationChannel<BaseMessage, *> {
just realized I can remove the *

2021-06-10 00:37 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private var HTTP_CLIENT: CloseableHttpClient = createHttpClient()
Tried but it will fail the test. Since the initialization is within `WebhookChannel` class, and for testing we need a way to assign the mockHttpClient to, so it has to be static so we can assign

2021-06-10 00:43 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/message/WebhookMessage.kt
> +    override fun toString(): String {
I have log here for failure case. `log.error("Exception sending message: $message", exception)`
That's why I override the toString(). Why this object shouldn't be logged, i didn't get that

2021-06-10 00:48 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/MessageContent.kt
> +    data class Attachment(
speratated out into one class

2021-06-10 22:18 UTC, akbhatta requested changes

2021-06-10 22:18 UTC, akbhatta commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/channel/client/ChannelHttpClient.kt
> +        private var HTTP_CLIENT: CloseableHttpClient = createHttpClient()
I believe having one connection does not work for parallel send case. please verify parallel execution of code.

2021-06-15 19:20 UTC, akbhatta approved these changes

2021-06-15 21:11 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/model/ChannelMessageResponse.kt
> +    val recipient: String? = null,
removed

2021-06-16 00:35 UTC, zhongnansu commented on notifications/spi/src/main/kotlin/org/opensearch/notifications/spi/client/DestinationHttpClientPool.kt
> +internal object DestinationHttpClientPool {
sure

2021-06-16 00:35 UTC, merged