Add release notes for 2.0.0.0-rc1
opensearch-project/notifications pull request #431
Opened 2022-04-25 21:57 UTC by qreshi

Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>

### Description
Add release notes for 2.0.0.0-rc1

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-25 23:10 UTC, Naarcha-AWS requested changes
Some changes and a question.

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +Notifications consists of `notifications-core` and `notifications` backend plugins for OpenSearch
Do we have download links to each?

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +and a `notificationsDashboards` frontend plugin for OpenSearch Dashboards.
Why is `notificationsDashboards` camelCase vs `notifications-code`?

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +This is the first official release of OpenSearch Notifications.
Change to "OpenSearch 2.0.0 is the first official release OpenSearch Notifications."

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +Notifications consists of `notifications-core` and `notifications` backend plugins for OpenSearch
Change to, "Notifications consist of three plugins, `notifications-core` and `notifications` backend plugins for OpenSearch, and a `notificationsDashboards` frontend plugin for OpenSearch Dashboards."

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +With Notifications you will be able to manage your notification channel configurations in a centralized location
Change to, "Use Notifications to manage your notification channel configurations in a centralized location..."

2022-04-25 23:10 UTC, Naarcha-AWS commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +Adds backend REST APIs for CRUD operations on channels and internal transport
"This release also adds notification-specifc REST APIs for CRUD operations on channels and internal transport APIs for integrating/communicating with other plugins."

2022-04-25 23:22 UTC, qreshi commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +Notifications consists of `notifications-core` and `notifications` backend plugins for OpenSearch
The documentation hasn't been written yet so I didn't have anything to link to here. It seems from the [opensearch downloads page](https://opensearch.org/downloads.html#opensearch) we only ever link whole distributions or min, not specific artifacts.

2022-04-25 23:22 UTC, qreshi commented on release-notes/opensearch-notifications.release-notes-2.0.0.0-rc1.md
> +and a `notificationsDashboards` frontend plugin for OpenSearch Dashboards.
It's the convention that was chose it seems for dashboard plugin naming vs backend. I was just using the plugin names so kept it consistent to that.

2022-04-25 23:31 UTC, Naarcha-AWS approved these changes

2022-04-25 23:56 UTC, lezzago approved these changes

2022-04-25 23:58 UTC, AWSHurneyt approved these changes

2022-04-26 00:05 UTC, dbbaughe approved these changes

2022-04-26 00:14 UTC, rishabhmaurya approved these changes

2022-04-26 00:16 UTC, merged