Add security tests and workflow plus minor fix
opensearch-project/notifications pull request #470
Opened 2022-07-05 13:57 UTC by lezzago

Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>

### Description
- Add security tests
- Add security github workflow
- Fix createNotificationConfig API requiring create indices permission

### Issues Resolved
#258

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-11 20:32 UTC, qreshi commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
> +        Assert.assertNotNull(error.get("reason").asString)
Should we check the error explicitly since this is technically testing an expected `INTERNAL_SERVER_ERROR` because the Slack channel doesn't exist.

Just want to make sure an actual issue presenting itself as an `INTERNAL_SERVER_ERROR` doesn't slip by in this case.

2022-08-03 23:38 UTC, qreshi commented on notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/NotificationConfigIndex.kt
> +            client.threadPool().threadContext.stashContext().use {
Tested this locally. This action was only needed for the create operation since it was attempting to create a security index if it didn't exist.

I tested the changes in this PR against `admin` and with a user with just create and list permissions and it worked as expected. So I think we're good.

2022-08-03 23:47 UTC, qreshi commented on .github/workflows/security-notifications-test-workflow.yml
> +            echo "Security plugin is NOT available skipping this run as tests without security have already been run"
Could we return an exit code of 1 here or something to treat the action as failed? If the test never ran and the GitHub Action is considered to be a success it might make it seem like the tests ran until we look at the output manually. This has happened in other repos before.

2022-08-04 18:51 UTC, lezzago commented on .github/workflows/security-notifications-test-workflow.yml
> +            echo "Security plugin is NOT available skipping this run as tests without security have already been run"
Added

2022-08-04 18:52 UTC, lezzago commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
> +        Assert.assertNotNull(error.get("reason").asString)
Done

2022-08-04 19:07 UTC, qreshi commented
The test and build dashboards CI is failing because it needs to build against 2.2 if we're using OSD branch `2.x`. We bumped our `2.x` branch to `2.2` but didn't do it to `main` since we were planning on bumping it `3.0` anyway. The bump to `3.0` is currently blocked on a bug being tracked in the OpenSearch repo as mentioned in https://github.com/opensearch-project/notifications/issues/481

If the bump to `3.0` remains blocked, we'll get `main` on to `2.2` in the meantime or update the CI to properly build against OSD `2.1`. The former would be the more consistent option since it would be strange to have our `2.x` branch ahead of `main` in version.

2022-08-04 19:10 UTC, qreshi approved these changes

2022-08-04 22:39 UTC, getsaurabh02 requested changes

2022-08-04 22:39 UTC, getsaurabh02 commented on notifications/notifications/src/main/kotlin/org/opensearch/notifications/index/NotificationConfigIndex.kt
> +@Suppress("TooGenericExceptionCaught")
Let's see if we can get rid of these Suppress by having more specific exceptions raised. Unless it is breaking bwc.

2022-08-04 22:39 UTC, getsaurabh02 commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/AccessRoles.kt
> +val NOTIFICATION_TEST_SEND_ACCESS = "notifications_test_send_access"
Why do we need to define these access roles separately/specifically for tests, and not import from the actual source for consistency ?

2022-08-04 22:39 UTC, getsaurabh02 commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/IntegTestHelpers.kt
> +fun getCreateRequestJsonString(
nit : should we be more specific in naming such as ``getCreateNotificationRequestJsonString``

2022-08-04 22:39 UTC, getsaurabh02 commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/IntegTestHelpers.kt
> +                "from_address":"$randomString@from.com"
Wondering if these all can be resolved via predefined Map <ConfigType, Value> for better maintainability and reusability ?

2022-08-04 22:39 UTC, getsaurabh02 commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
> +    fun `test delete slack notification config without get Notification permission`() {
Wondering if we should randomize on the channels; since all the scenarios will fit across different channels (slack/chime)

2022-08-04 22:43 UTC, lezzago commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/AccessRoles.kt
> +val NOTIFICATION_TEST_SEND_ACCESS = "notifications_test_send_access"
This is purely as a helper class. Only the `ALL_ACCESS_ROLE`, `NOTIFICATION_FULL_ACCESS_ROLE`, and `NOTIFICATION_READ_ONLY_ACCESS` exist, but that is in the security plugin. We have set the others so it easier for the security integration tests to use them.

2022-08-05 00:03 UTC, lezzago commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
> +    fun `test delete slack notification config without get Notification permission`() {
I agree. In a future PR, we can make the tests run for each channel type

2022-08-05 00:08 UTC, lezzago commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/IntegTestHelpers.kt
> +                "from_address":"$randomString@from.com"
The problem is that we need to pass in values to the config definition and abstracting this out would end up complicating the code as no other function currently needs this.

2022-08-05 01:07 UTC, qreshi approved these changes

2022-08-05 01:13 UTC, getsaurabh02 commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/SecurityNotificationIT.kt
> +    fun `test delete slack notification config without get Notification permission`() {
Lets create a backlog.

2022-08-05 01:14 UTC, getsaurabh02 approved these changes

2022-08-05 01:14 UTC, merged