Bump to 3.0
opensearch-project/notifications pull request #556
Opened 2022-10-27 15:27 UTC by lezzago

Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>

### Description
Bump version to 3.0

### Issues Resolved
#481 

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-15 20:02 UTC, reta commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
```suggestion
    compileOnly "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
    compileOnly "com.fasterxml.jackson.core:jackson-annotations:${versions.jackson}"
```

Otherwise, JarHell due to https://github.com/opensearch-project/OpenSearch/pull/5366

2022-12-15 20:05 UTC, reta requested changes

2022-12-15 20:05 UTC, reta commented on notifications/core/build.gradle
>          force "com.fasterxml.jackson.core:jackson-annotations:${versions.jackson}" // resolve for amazonaws
Please change:

```
force "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.11.4" // resolve for amazonaws
force "com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.11.4" // resolve for amazonaws
force "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.11.4" // resolve for amazonaws
```

to 

```
force "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:${versions.jackson}" // resolve for amazonaws
force "com.fasterxml.jackson.dataformat:jackson-dataformat-smile:${versions.jackson}" // resolve for amazonaws
force "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${versions.jackson}" // resolve for amazonaws
```

2022-12-15 20:07 UTC, qreshi commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
Is the OpenSearch 3.0 snapshot that's already available contain the change in the PR above already? I ran the build and test for the Notifications test in this PR already and didn't hit any jarhell issues.

2022-12-15 20:09 UTC, reta commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
Yes, it does

2022-12-15 20:10 UTC, reta commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
> I ran the build and test for the Notifications test in this PR already and didn't hit any jarhell issues.

Did you build the Docker container for `opensearch-notifications:test`?

2022-12-15 21:08 UTC, qreshi commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
[Our workflow](https://github.com/opensearch-project/notifications/blob/main/.github/workflows/security-notifications-test-workflow.yml#L55-L69) pulls the staging image and replaces (or adds if it's not present) the Notification plugin with the changes in the PR it's running for.

2022-12-15 21:10 UTC, reta commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
I think if you restart the workflow, you will see the problem - my local image build failed for this pull request with JarHell

2022-12-15 21:16 UTC, reta commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
Interesting, it seems like that snapshots are old? These warnings (which led to issues) where also fixed in 3.0.0

```
WARNING: Illegal reflective access by org.apache.hc.core5.util.ReflectionUtils$1 (file:/home/runner/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents.core5/httpcore5/5.1.5/df9da3a1fa2351c4790245400ed28d78a8ddd3fc/httpcore5-5.1.5.jar) to method sun.security.ssl.SSLEngineImpl.getApplicationProtocol()
> Task :notifications:integTest
WARNING: Illegal reflective access by org.apache.hc.core5.util.ReflectionUtils$1 (file:/home/runner/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents.core5/httpcore5/5.1.5/df9da3a1fa2351c4790245400ed28d78a8ddd3fc/httpcore5-5.1.5.jar) to method sun.security.ssl.SSLEngineImpl.getApplicationProtocol()
```

2022-12-16 20:20 UTC, qreshi commented on notifications/core/build.gradle
>      implementation "com.fasterxml.jackson.core:jackson-databind:${versions.jackson_databind}"
My local build/tests are still passing. I'm going to leave these as they are for now. If we end up seeing issues in the distribution build later on, I'll follow-up then.

2022-12-16 20:23 UTC, qreshi commented
Given that the only failures are known flaky tests from the OpenSearch Dashboards side and the errors on the security test CI which is being tracked in https://github.com/opensearch-project/notifications/issues/580, let's merge this in to bump Notifications to 3.0 and unblock downstream plugins and continue investigating https://github.com/opensearch-project/notifications/issues/580 and follow-up on that afterwards since it seems to be coming from a core dependency change and not from Notifications itself.

2022-12-16 20:23 UTC, qreshi approved these changes

2022-12-16 20:31 UTC, rishabhmaurya approved these changes

2022-12-16 20:31 UTC, merged