Add unit integ test for feature support ms teams
opensearch-project/notifications pull request #638
Opened 2023-02-24 20:02 UTC by dankyalo599

### Description
[FEATURE] Support Microsoft Teams webhooks #585
### Issues Resolved
Add unit and integTest for feature support ms teams

### Check List
- [ X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-12 02:24 UTC, Hailong-am commented
depends on https://github.com/opensearch-project/common-utils/pull/374

2023-04-12 03:46 UTC, Hailong-am commented on notifications/notifications/src/test/kotlin/org/opensearch/notifications/ObjectEqualsHelpers.kt
> +        ConfigType.MICROSOFT_TEAMS -> verifyEquals((config.configData as Microsoft_teams), jsonObject.get("microsoft_teams").asJsonObject)
same here, should be `MicrosoftTeams`

2023-04-12 03:50 UTC, Hailong-am commented on notifications/core/src/test/kotlin/org/opensearch/notifications/core/destinations/MicrosofTeamsDestinationTests.kt
> +
missing import here.

2023-04-12 03:52 UTC, Hailong-am commented on notifications/core/src/test/kotlin/org/opensearch/notifications/core/destinations/MicrosofTeamsDestinationTests.kt
> +/*
this is a duplicate with [MicrosoftTeamsDestinationTests.kt](https://github.com/opensearch-project/notifications/pull/638/files#diff-c2954fed5ee706eae7ade0b833d6775a2d23da2f23c167be4dc8ef0fbce0efd4), please remove it.

2023-04-12 03:55 UTC, zhichao-aws requested changes
Great work, but need some changes. Besides the issues I mentioned in the comments, there are still some bugs, such as not establishing a mapping in DestinationTransportProvider. The current code cannot pass the code style check (kotlint) and compilation. And it also can not work. Please fix your build and run tests locally.

BTW, you can directly add new comments to this PR, don't need to create new PR :)

2023-04-12 03:55 UTC, zhichao-aws commented on notifications/core-spi/src/test/kotlin/org/opensearch/notifications/spi/utils/ValidationHelpersTests.kt
> +    @Test
Functions should be separated by a blank line.

2023-04-12 03:55 UTC, zhichao-aws commented on notifications/notifications/src/main/kotlin/org/opensearch/notifications/send/SendMessageActionHelper.kt
> +//            LegacyDestinationType.LEGACY_CUSTOM_WEBHOOK -> {
we can remove these comments

2023-04-12 03:55 UTC, zhichao-aws commented on notifications/notifications/src/test/kotlin/org/opensearch/integtest/send/SendTestMessageRestHandlerIT.kt
> +    @Suppress("EmptyFunctionBlock")
we can remove this one and only keep the first test. Besides, we shouldn't put real webhook in code

2023-05-16 03:42 UTC, zhichao-aws commented
Hi, I create a new [PR](https://github.com/opensearch-project/notifications/pull/676) to fix the build, and add more integTest. Close this one.

2023-05-16 03:42 UTC, closed without merging