Refactor for reduce scattered channel data
opensearch-project/notifications pull request #7
Opened 2021-04-22 15:42 UTC by jayeshathila

### Description
Moved notification types to be of enum which will make it easier to add new channel. As of now the code is scattered and for single channel addition we have to make changes at multiple places. After this change we will only have to make changes in single file (ideally) in config flow.

### Issues Resolved
NA

### Check List (TBD)
- [ ] New functionality includes testing.
- [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
- [ ] New functionality has javadoc added
- [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-04-22 16:46 UTC, akbhatta requested changes
Please add Java Doc to all public classes/interfaces

2021-04-22 16:46 UTC, akbhatta commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/BaseChannelData.kt
> +package org.opensearch.commons.notifications.model
is this interface required? why not use BaseModel itself?

If it is required can we rename this to BaseConfigData?

Also license header missing

2021-04-22 16:46 UTC, akbhatta commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
> +        val channelDataList: List<BaseChannelData?> = listOf(),
This need not be list. we are interested only in object corresponding to ConfigType.
may be we can have a configData as single object

2021-04-22 16:46 UTC, akbhatta commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/ChannelProperties.kt
> +val SlackChannelProperties = object : ChannelProperties {
can we move this to new package? May be ChannelDataFactory also belongs to that package
also can this be split into multiple files?

2021-04-22 16:57 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
> +        val channelDataList: List<BaseChannelData?> = listOf(),
In that case, can we simply remote the `ConfigType` here ?

2021-04-22 16:57 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/BaseChannelData.kt
> +package org.opensearch.commons.notifications.model
`BaseModel` is at many other places which aren't necessarily Data class.

Ya we can rename it though.

2021-04-22 16:58 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/ChannelProperties.kt
> +val SlackChannelProperties = object : ChannelProperties {
Yes, will move it to separate package.

2021-04-23 18:32 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
> +        val channelDataList: List<BaseChannelData?> = listOf(),
Also I see we have test cases with multiple configData in them which says we can list of `ConfigData`.

2021-04-26 17:01 UTC, akbhatta requested changes

2021-04-26 17:01 UTC, akbhatta commented on notifications/src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigTests.kt
>          val jsonString = """
I am not sure how newly introduced tag "configData" is used?

2021-04-26 17:01 UTC, akbhatta commented on notifications/src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigTests.kt
>      fun `Config serialize and deserialize with disabled multiple json objects should be equal`() {
I believe these test cases are no more valid. multiple json objects are no more supported right?

2021-04-26 18:09 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/config/ConfigProperties.kt
> +val SlackChannelProperties = object : ChannelProperties {
Moving it to separate file won't add much value IMO. We can move it once it seems bloated.

2021-04-26 18:18 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/Chime.kt
> +        fun parse(configDataMap: Map<String, Any>): Chime {
But that will be unused method, we can always get it from history if and when needed.

2021-04-26 19:45 UTC, akbhatta commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/Chime.kt
> +        fun parse(configDataMap: Map<String, Any>): Chime {
It will be used when storing into the index/reading from index I believe.

2021-04-27 08:53 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/Chime.kt
> +        fun parse(configDataMap: Map<String, Any>): Chime {
Done

2021-04-27 08:53 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/Chime.kt
> +        val url: String
Done

2021-04-27 08:54 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
> +        const val CONFIG_DATA_TAG = "configData"
Done

2021-04-27 08:54 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
> +        if (configType === ConfigType.None) {
Done

2021-04-27 08:54 UTC, jayeshathila commented on notifications/src/main/kotlin/org/opensearch/commons/notifications/model/config/ConfigProperties.kt
> +val CONFIG_PROPERTIES: List<ChannelProperties> = listOf(
Done

2021-04-27 08:54 UTC, jayeshathila commented on notifications/src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigTests.kt
>          val jsonString = """
Discussed over call.

2021-04-28 21:47 UTC, jayeshathila commented
Closing this bloated PR in favour of - https://github.com/opensearch-project/notifications/pull/9

2021-04-28 21:47 UTC, closed without merging