adding hostname support for notifications deny list
opensearch-project/notifications pull request #858
Opened 2024-02-13 22:01 UTC by toepkerd

### Description
Adds support for checking hostnames in a customer's deny list, in addition to the existing functionality of checking IP addresses.

### Issues Resolved
Action item for internal security vulnerability.

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-13 22:35 UTC, toepkerd commented
In regards to the failing CIs, when built locally, the repo with my changes stashed away failed on the same BWC task for the same reasons:

```
:notifications:notificationsBwcCluster#mixedClusterTask
Caused by: org.opensearch.gradle.testclusters.TestClustersException: `cluster{:notifications:notificationsBwcCluster0}` failed to wait for cluster health yellow after 40 SECONDS
  IO error while waiting cluster
  503 Service Unavailable
```

2024-02-14 20:42 UTC, eirsep commented on notifications/core/src/main/kotlin/org/opensearch/notifications/core/utils/ValidationHelpers.kt
> +            if (denyIpStr.contains(ipStr) || denyHostStr.equals(hostStr)) {
plz add error log if this condition is true and log the url that got denied

2024-02-14 20:43 UTC, eirsep commented on notifications/core/src/test/kotlin/org/opensearch/notifications/core/utils/ValidationHelpersTests.kt
> +            assertEquals(true, isHostInDenylist("https://$ip", hostDenyList), "for hostname $ip")
what is  `"for hostname $ip"`

2024-02-14 22:23 UTC, toepkerd commented on notifications/core/src/main/kotlin/org/opensearch/notifications/core/utils/ValidationHelpers.kt
> +            if (denyIpStr.contains(ipStr) || denyHostStr.equals(hostStr)) {
done

2024-02-14 22:28 UTC, eirsep requested changes

2024-02-14 22:28 UTC, eirsep commented on notifications/core/src/main/kotlin/org/opensearch/notifications/core/utils/ValidationHelpers.kt
> +                LogManager.getLogger().error("${url.host} is denied")
Can 
plz initialize logger for the class else we can't 
`private val logger = LogManager.getLogger(ValidationHelpers::class.java)` and use it.

2024-02-14 22:35 UTC, eirsep approved these changes

2024-02-14 23:10 UTC, sbcd90 commented on notifications/core/src/test/kotlin/org/opensearch/notifications/core/utils/ValidationHelpersTests.kt
> +    fun `test hosts not in denylist`() {
can we add a test case which demonstrates the additional checks hostname.equals is doing other than normal string.equals?

2024-02-14 23:11 UTC, sbcd90 approved these changes

2024-02-15 01:14 UTC, praveensameneni approved these changes

2024-02-15 18:44 UTC, merged